apiVersion: v1
kind: Namespace
metadata:
    name: kason-be-infrastructure

---

apiVersion: v1
kind: Namespace
metadata:
    name: kason-be-business

---

apiVersion: v1
kind: Namespace
metadata:
    name: kason-fe
