apiVersion: apps/v1
kind: Deployment
metadata:
  name: kason-eureka
  namespace: kason-be-business
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kason-eureka
    matchExpressions:
    - {key: app, operator: In, values: [kason-eureka] }
  template:
    metadata:
      labels:
        app: kason-eureka
    spec:
      containers:
      - name: kason-eureka
        image: kason-eureka:2.0
        ports:
        - containerPort: 8762
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: kason-eureka-claim
      volumes:
      - name: kason-eureka-claim
        hostPath:
          path: /root/docker/kason/eureka/logs
status: {}