apiVersion: v1
kind: Service
metadata:
  labels:
    app: kason-config
  name: kason-config
  namespace: kason-be-business
spec:
  type: NodePort
  ports:
  - name: "7771"
    port: 7771
    targetPort: 7771
    nodePort: 31001
  selector:
    app: kason-config
status:
  loadBalancer: {}
