apiVersion: v1
kind: Service
metadata:
  labels:
    app: kason-eureka
  name: kason-eureka
  namespace: kason-be-business
spec:
  type: NodePort
  ports:
  - name: "8762"
    port: 8762
    targetPort: 8762
    nodePort: 31001
  selector:
    app: kason-eureka
status:
  loadBalancer: {}