spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(2PE/BMMoNPbRCEaIyGfcSw==)
    password: ENC(zF1rDpn+u8RZX5OTor7BpHzprZyrH+3P)
    url: jdbc:mysql://${DB_IP}:3306/kason_db?allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Pacific/Auckland
    hikari:
      max-lifetime: 60000
      connection-timeout: 60000
      maximum-pool-size: 10

me:
  fengorz:
    file:
      crawler:
        voice:
          tmpPath: "/wordTmp"
      vocabulary:
        word:
          list:
            path: "/wordTmp"



